# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://github.com/NG-Development/ngdevelopment
title: NGDevelopment
email: NGDevelopment
author: NGDevelopment
description: > # "This is our project for CSE 442. Our team worked closely with Northrop
Grumman to create a 3D Antenna Visualization Tool.
copyright: 'Copyright &copy; 2017 NGDevelopment. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Download 
    url: UI.zip
  - title: github
    url: https://github.com/NG-Development/ngdevelopment
  - title: Models
    url: Models.rar
