# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://github.com/NG-Development/ngdevelopment
title: NGDevelopment
email: NGDevelopment
author: NGDevelopment
description: > # "Landing Page for our CSE 442 Project. 
  This is our CSE 442 project. Our team was working closely with  
  Northrop Grumman to create a 3D Antenna Visualization Tool. 
copyright: 'Copyright &copy; 2017 NGDevelopment. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Windows 
    url: UI.zip
  - title: apple
    url: UI.zip
  - title: github
    url: https://github.com/NG-Development/ngdevelopment
